export const listData = {
    rows: [
      {
        name: "name 1",
        age: 88,
        telephone: "telephone 1",
        location: "location 1",
        id: "1",
      },
      {
        name: "name 2",
        age: 37,
        telephone: "telephone 2",
        location: "location 2",
        id: "2",
      },
      {
        name: "name 3",
        age: 5,
        telephone: "telephone 3",
        location: "location 3",
        id: "3",
      },
      {
        name: "name 4",
        age: 4,
        telephone: "telephone 4",
        location: "location 4",
        id: "4",
      },
      {
        name: "name 5",
        age: 16,
        telephone: "telephone 5",
        location: "location 5",
        id: "5",
      },
      {
        name: "name 6",
        age: 1,
        telephone: "telephone 6",
        location: "location 6",
        id: "6",
      },
      {
        name: "name 7",
        age: 7,
        telephone: "telephone 7",
        location: "location 7",
        id: "7",
      },
      {
        name: "name 8",
        age: 16,
        telephone: "telephone 8",
        location: "location 8",
        id: "8",
      },
      {
        name: "name 9",
        age: 35,
        telephone: "telephone 9",
        location: "location 9",
        id: "9",
      },
      {
        name: "name 10",
        age: 75,
        telephone: "telephone 10",
        location: "location 10",
        id: "10",
      },
      {
        name: "name 11",
        age: 26,
        telephone: "telephone 11",
        location: "location 11",
        id: "11",
      },
      {
        name: "name 12",
        age: 30,
        telephone: "telephone 12",
        location: "location 12",
        id: "12",
      },
      {
        name: "name 13",
        age: 80,
        telephone: "telephone 13",
        location: "location 13",
        id: "13",
      },
      {
        name: "name 14",
        age: 22,
        telephone: "telephone 14",
        location: "location 14",
        id: "14",
      },
      {
        name: "name 15",
        age: 74,
        telephone: "telephone 15",
        location: "location 15",
        id: "15",
      },
      {
        name: "name 16",
        age: 74,
        telephone: "telephone 16",
        location: "location 16",
        id: "16",
      },
      {
        name: "name 17",
        age: 77,
        telephone: "telephone 17",
        location: "location 17",
        id: "17",
      },
      {
        name: "name 18",
        age: 61,
        telephone: "telephone 18",
        location: "location 18",
        id: "18",
      },
      {
        name: "name 19",
        age: 55,
        telephone: "telephone 19",
        location: "location 19",
        id: "19",
      },
      {
        name: "name 20",
        age: 89,
        telephone: "telephone 20",
        location: "location 20",
        id: "20",
      },
      {
        name: "name 21",
        age: 1,
        telephone: "telephone 21",
        location: "location 21",
        id: "21",
      },
      {
        name: "name 22",
        age: 85,
        telephone: "telephone 22",
        location: "location 22",
        id: "22",
      },
      {
        name: "name 23",
        age: 22,
        telephone: "telephone 23",
        location: "location 23",
        id: "23",
      },
      {
        name: "name 24",
        age: 49,
        telephone: "telephone 24",
        location: "location 24",
        id: "24",
      },
      {
        name: "name 25",
        age: 25,
        telephone: "telephone 25",
        location: "location 25",
        id: "25",
      },
      {
        name: "name 26",
        age: 49,
        telephone: "telephone 26",
        location: "location 26",
        id: "26",
      },
      {
        name: "name 27",
        age: 3,
        telephone: "telephone 27",
        location: "location 27",
        id: "27",
      },
      {
        name: "name 28",
        age: 34,
        telephone: "telephone 28",
        location: "location 28",
        id: "28",
      },
      {
        name: "name 29",
        age: 68,
        telephone: "telephone 29",
        location: "location 29",
        id: "29",
      },
      {
        name: "name 30",
        age: 50,
        telephone: "telephone 30",
        location: "location 30",
        id: "30",
      },
      {
        name: "name 31",
        age: 40,
        telephone: "telephone 31",
        location: "location 31",
        id: "31",
      },
      {
        name: "name 32",
        age: 98,
        telephone: "telephone 32",
        location: "location 32",
        id: "32",
      },
      {
        name: "name 33",
        age: 93,
        telephone: "telephone 33",
        location: "location 33",
        id: "33",
      },
      {
        name: "name 34",
        age: 60,
        telephone: "telephone 34",
        location: "location 34",
        id: "34",
      },
      {
        name: "name 35",
        age: 54,
        telephone: "telephone 35",
        location: "location 35",
        id: "35",
      },
      {
        name: "name 36",
        age: 84,
        telephone: "telephone 36",
        location: "location 36",
        id: "36",
      },
      {
        name: "name 37",
        age: 94,
        telephone: "telephone 37",
        location: "location 37",
        id: "37",
      },
      {
        name: "name 38",
        age: 83,
        telephone: "telephone 38",
        location: "location 38",
        id: "38",
      },
      {
        name: "name 39",
        age: 75,
        telephone: "telephone 39",
        location: "location 39",
        id: "39",
      },
      {
        name: "name 40",
        age: 19,
        telephone: "telephone 40",
        location: "location 40",
        id: "40",
      },
      {
        name: "name 41",
        age: 78,
        telephone: "telephone 41",
        location: "location 41",
        id: "41",
      },
      {
        name: "name 42",
        age: 19,
        telephone: "telephone 42",
        location: "location 42",
        id: "42",
      },
      {
        name: "name 43",
        age: 1,
        telephone: "telephone 43",
        location: "location 43",
        id: "43",
      },
      {
        name: "name 44",
        age: 47,
        telephone: "telephone 44",
        location: "location 44",
        id: "44",
      },
      {
        name: "name 45",
        age: 47,
        telephone: "telephone 45",
        location: "location 45",
        id: "45",
      },
      {
        name: "name 46",
        age: 30,
        telephone: "telephone 46",
        location: "location 46",
        id: "46",
      },
      {
        name: "name 47",
        age: 52,
        telephone: "telephone 47",
        location: "location 47",
        id: "47",
      },
      {
        name: "name 48",
        age: 35,
        telephone: "telephone 48",
        location: "location 48",
        id: "48",
      },
      {
        name: "name 49",
        age: 44,
        telephone: "telephone 49",
        location: "location 49",
        id: "49",
      },
      {
        name: "name 50",
        age: 35,
        telephone: "telephone 50",
        location: "location 50",
        id: "50",
      },
    ],
    page: 1,
    limit: 1,
    total: 50,
    totalPages: 10,
  };